# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FreeGiving' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FreeGiving

  pod 'SwiftLint'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'IQKeyboardManagerSwift', '4.0.10'
  pod 'SwifterSwift'
  pod 'SDWebImage', '~> 4.0'
  pod 'Floaty', '~> 3.0'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'BEMCheckBox'
  pod 'SCLAlertView'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'FBAnnotationClusteringSwift'

end
